import { StyleSheet } from 'react-native';
import { colors, spacing, radius, shadow } from '../../constants/theme';

export const worldStyles = StyleSheet.create({
  coinBadge: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 20,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(0.75),
  },
  coinText: { fontWeight: '700', color: '#fff' },
  emptyText: { textAlign: 'center', color: colors.muted },
  plantGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  plantCell: {
    width: 56,
    height: 56,
    borderRadius: radius.md,
    backgroundColor: colors.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  plantEmoji: { fontSize: 26 },
  sectionLabel: {
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing(1),
    marginTop: spacing(1),
    textAlign: 'right',
  },
  shopGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  shopItem: {
    width: 88,
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.soft,
  },
  shopItemDisabled: { opacity: 0.4 },
  shopEmoji: { fontSize: 28, marginBottom: 4 },
  shopLabel: { fontSize: 12, color: colors.text, fontWeight: '600' },
  shopCost: { fontSize: 11, color: colors.muted, marginTop: 2 },
  capacityText: { textAlign: 'right', color: colors.muted, marginBottom: spacing(1) },
  avatarRow: { flexDirection: 'row', gap: 16, justifyContent: 'center', marginBottom: spacing(2) },
  avatarPreview: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: radius.md,
    padding: spacing(2),
    borderWidth: 1,
    borderColor: colors.border,
    width: 120,
    ...shadow.soft,
  },
  avatarBody: { fontSize: 44 },
  avatarHat: { fontSize: 20, position: 'absolute', top: 10 },
  avatarName: { marginTop: spacing(1), color: colors.muted, fontSize: 12 },
  optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: spacing(1) },
  optionCell: {
    width: 48,
    height: 48,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  optionCellActive: { borderColor: colors.primary, borderWidth: 2 },
  colorCell: { width: 36, height: 36, borderRadius: 18 },
  colorCellActive: { borderWidth: 3, borderColor: colors.text },
});
