import { StyleSheet } from 'react-native';
import { colors, spacing, radius, shadow } from '../../constants/theme';

export const momentsStyles = StyleSheet.create({
  empty: { textAlign: 'center', color: colors.muted, marginTop: spacing(6) },
  momentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing(1.5),
  },
  momentThumb: {
    width: 48,
    height: 48,
    borderRadius: radius.sm,
    backgroundColor: '#FDEDEF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: spacing(1.5),
  },
  momentTitle: { fontWeight: '700', color: colors.text, textAlign: 'right' },
  momentSub: { color: colors.muted, fontSize: 12, textAlign: 'right', marginTop: 2 },
  fabWrap: {
    position: 'absolute',
    bottom: spacing(3),
    right: spacing(3),
  },
  fab: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow.lift,
  },
  cameraBar: {
    position: 'absolute',
    bottom: 30,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  cameraCancel: { padding: 10 },
  cameraFlip: { padding: 10 },
  shutter: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#fff',
    borderWidth: 4,
    borderColor: '#ccc',
    alignSelf: 'center',
    position: 'absolute',
    left: '50%',
    marginLeft: -37,
  },
  captionBar: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  captionInput: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    color: '#fff',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewerCaption: {
    position: 'absolute',
    bottom: 60,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 12,
    borderRadius: radius.sm,
  },
  viewerClose: { position: 'absolute', top: 50, right: 20 },
});
